on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  mirror:
    name: "Mirror"
    runs-on: ubuntu-latest
    steps:
      - name: "Clone"
        run: |
          git clone --mirror https://gitlab.gnome.org/GNOME/pango.git .
      - name: "Push"
        env:
          OSMERION_CI_ACCOUNT_NAME: ${{ secrets.OSMERION_CI_ACCOUNT_NAME }}
          OSMERION_CI_ACCOUNT_TOKEN: ${{ secrets.OSMERION_CI_ACCOUNT_TOKEN }}
        run: |
          git remote set-url origin https://$OSMERION_CI_ACCOUNT_NAME:$OSMERION_CI_ACCOUNT_TOKEN@github.com/Osmerion/pango
          git push -f --mirror origin